GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsIm5hbWUiOiJEYXJhICIsImVtYWlsIjoiZGFyYUBnbWFpbC5jb20iLCJpYXQiOjE2Nzc2NDYwMTAsImV4cCI6MTY3NzY0NjAzMH0.wO9NEl86Vch79ic4neh2sPWqU1Yln5bQmuvxDSOtg6w
###
POST http://localhost:5000/users
Content-Type: application/json

{
  "name": "Dara ",
  "email": "dara@gmail.com",
  "password": "1",
  "confPassword": "1"
}


###
POST http://localhost:5000/login
Content-Type: application/json

{
  "email":"dara@gmail.com",
  "password":"1"
}

